version: '3.3'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  kong-migration:
    image: kong:3.3
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap

  kong:
    image: kong:3.3
    container_name: kong
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    ports:
      - "9000:8000"
      - "8001:8001"
    # REMOVE or comment out this line
    # volumes:
    #   - kong-logs:/usr/local/kong/logs
    restart: always

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - konga-mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always

  konga:
    image: pantsel/konga:latest
    container_name: konga
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      DB_ADAPTER: mongo
      DB_HOST: mongo
      DB_PORT: 27017
      DB_DATABASE: konga_db
    ports:
      - "1337:1337"
    restart: always

  p21-api:
    build:
      context: ./p21-api
    container_name: p21-api
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./p21-api/.env

volumes:
  kong-db-data:
  konga-mongo-data:
#  kong-logs:
