
CREATE TABLE [dbo].[TMP_SRX_Header] (
    [Import_Set_No] NVARCHAR(8) NOT NULL,
    [Customer_ID] DECIMAL(18,2) NOT NULL,
    [Customer_Name] NVARCHAR(50) NULL,
    [Company_ID] NVARCHAR(8) NOT NULL,
    [Sales_Location_ID] DECIMAL(18,2) NOT NULL,
    [Customer_PO_Number] NVARCHAR(50) NULL,
    [Contact_ID] NVARCHAR(16) NULL,
    [Contact_Name] NVARCHAR(50) NULL,
    [Taker] NVARCHAR(30) NULL,
    [Job_Name] NVARCHAR(40) NULL,
    [Order_Date] NVARCHAR(8) NULL,
    [Requested_Date] NVARCHAR(8) NULL,
    [Quote] NVARCHAR(1) NULL,
    [Approved] NVARCHAR(1) NOT NULL,
    [Ship_To_ID] DECIMAL(18,2) NOT NULL,
    [Ship_To_Name] NVARCHAR(50) NULL,
    [Ship_To_Address_1] NVARCHAR(50) NULL,
    [Ship_To_Address_2] NVARCHAR(50) NULL,
    [Ship_To_City] NVARCHAR(50) NULL,
    [Ship_To_State] NVARCHAR(50) NULL,
    [Ship_To_Zip_Code] NVARCHAR(10) NULL,
    [Ship_To_Country] NVARCHAR(50) NULL,
    [Source_Location_ID] DECIMAL(18,2) NULL,
    [Carrier_ID] DECIMAL(18,2) NULL,
    [Carrier_Name] NVARCHAR(50) NULL,
    [Route] NVARCHAR(255) NULL,
    [Packing_Basis] NVARCHAR(16) NULL,
    [Delivery_Instructions] NVARCHAR(255) NULL,
    [Terms] NVARCHAR(2) NULL,
    [Terms_Desc] NVARCHAR(20) NULL,
    [Will_Call] NVARCHAR(1) NULL,
    [Class_1] NVARCHAR(8) NULL,
    [Class_2] NVARCHAR(8) NULL,
    [Class_3] NVARCHAR(8) NULL,
    [Class_4] NVARCHAR(8) NULL,
    [Class_5] NVARCHAR(8) NULL,
    [RMA_Flag] NVARCHAR(1) NULL,
    [Freight_Code] NVARCHAR(30) NULL,
    [Third_Party_Billing_Flag_Desc] NVARCHAR(40) NULL,
    [Capture_Usage_Default] NVARCHAR(1) NULL,
    [Allocate] NVARCHAR(1) NULL,
    [Contract_Number] NVARCHAR(255) NOT NULL,
    [Invoice_Batch_Number] NVARCHAR(255) NULL,
    [Ship_To_Email_Address] NVARCHAR(255) NULL,
    [Set_Invoice_Exchange_Rate_Source_Desc] NVARCHAR(40) NULL,
    [Ship_To_Phone] NVARCHAR(20) NULL,
    [Currency_ID] NVARCHAR(255) NULL,
    [Apply_Builder_Allowance_Flag] NVARCHAR(1) NULL,
    [Quote_Expiration_Date] NVARCHAR(8) NULL,
    [Promise_Date] NVARCHAR(8) NULL,
    CONSTRAINT [PK_OrderQuoteHeader] PRIMARY KEY CLUSTERED ([Import_Set_No])
);

GO

CREATE TABLE [dbo].[TMP_SRX_Line] (
    [Import_Set_Number] NVARCHAR(8) NOT NULL,
    [Line_No] DECIMAL(18,2) NOT NULL,
    [Item_ID] NVARCHAR(40) NOT NULL,
    [Unit_Quantity] DECIMAL(18,2) NOT NULL,
    [Unit_of_Measure] NVARCHAR(8) NOT NULL,
    [Unit_Price] NVARCHAR(255) NULL,
    [Extended_Description] NVARCHAR(255) NULL,
    [Source_Location_ID] DECIMAL(18,2) NULL,
    [Ship_Location_ID] DECIMAL(18,2) NULL,
    [Product_Group_ID] NVARCHAR(8) NULL,
    [Supplier_ID] DECIMAL(18,2) NULL,
    [Supplier_Name] NVARCHAR(50) NULL,
    [Required_Date] NVARCHAR(8) NULL,
    [Expedite_Date] NVARCHAR(8) NULL,
    [Will_Call] NVARCHAR(1) NULL,
    [Tax_Item] NVARCHAR(1) NULL,
    [OK_to_Interchange] NVARCHAR(1) NULL,
    [Pricing_Unit] NVARCHAR(8) NULL,
    [Commission_Cost] NVARCHAR(255) NULL,
    [Other_Cost] NVARCHAR(255) NULL,
    [PO_Cost] NVARCHAR(255) NULL,
    [Disposition] NVARCHAR(1) NULL,
    [Scheduled] NVARCHAR(1) NULL,
    [Manual_Price_Override] NVARCHAR(1) NULL,
    [Commission_Cost_Edited] NVARCHAR(1) NULL,
    [Other_Cost_Edited] NVARCHAR(1) NULL,
    [Capture_Usage] NVARCHAR(1) NULL,
    [Tag_and_Hold_Class_ID] NVARCHAR(8) NULL,
    [Contract_Bin_ID] NVARCHAR(8) NULL,
    [Contract_No] NVARCHAR(8) NULL,
    [Allocation_Qty] DECIMAL(18,2) NULL,
    [Promise_Date] NVARCHAR(8) NULL,
    CONSTRAINT [PK_OrderQuoteLine] PRIMARY KEY CLUSTERED ([Item_ID])
);

GO
